Controllers/AppController.cs
using AceSchoolPortal.Data;
using AceSchoolPortal.Data.Entities;
using AceSchoolPortal.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class AppController : Controller
    {
        private readonly ISchoolRepository _repository;
        private readonly SchoolContext db;

        public AppController(ISchoolRepository repository, SchoolContext db)
        {
            _repository = repository;
            this.db = db;
        }

        public IActionResult index()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }
        public IActionResult NotEnabled()
        {
            return View();
        }

        public IActionResult NewRegistration()
        {
            return View();
        }

        public IActionResult NewStudent()
        {
            return View();
        }

        public async Task<IActionResult> UserManagement(string searchString)
        {
            ViewBag.Title = "Shop";
            var results = /*from p in _context*/_repository/*.Products*/.GetAllUsers();
            //orderby p.Category
            //select p;

            /* for filter by name */
            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                results = results.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString));
            }

            return View(results.ToList());
        }

        public IActionResult StudentManagement()
        {
            ViewBag.Title = "Shop";
            var results = /*from p in _context*/_repository/*.Products*/.GetAllStudents();
            //orderby p.Category
            //select p;

            return View(results.ToList());
        }

        [HttpPost]
        public IActionResult NewRegistration(NewRegstnViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newUser = new Users()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    EmailAddress = model.Email,
                    UserName = model.Email,
                    Password = model.Password,
                    ContactNo = model.ContactNo
                };

                _repository.AddEntity(newUser);
                _repository.SaveAll();

            }
            else
            {
                //show errors
            }
            return View();
        }


        public IActionResult Edit(string id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.ListAllUsers().Where(u => u.UserName == id).FirstOrDefault();

            return View(usr);
        }

        [HttpPost]
        public ActionResult Edit(Users usr)
        {
            //update user in DB using EntityFramework in real-life application

            //update list by removing old user and adding updated user for demo purpose
            var user = _repository.ListAllUsers().Where(u => u.UserName == usr.UserName).FirstOrDefault();
            _repository.RemoveEntity(user);
            _repository.AddEntity(usr);
            _repository.SaveAll();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(string id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.ListAllUsers().Where(u => u.UserName == id).FirstOrDefault();
            return View(usr);
        }

        [HttpPost]
        public ActionResult Delete(Users usr)
        {
            //update student in DB using EntityFramework in real-life application

            //update list by removing old student and adding updated student for demo purpose
            var user = _repository.ListAllUsers().Where(u => u.UserName == usr.UserName).FirstOrDefault();
            _repository.RemoveEntity(user);
            _repository.SaveAll();

            return RedirectToAction("Index");
        }
    }
 }

Controllers/InstructorController.cs
using AceSchoolPortal.Data;
using AceSchoolPortal.Data.Entities;
using AceSchoolPortal.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class InstructorController : Controller
    {
        private readonly ISchoolRepository _repository;
        private readonly SchoolContext db;

        public InstructorController(ISchoolRepository repository, SchoolContext db)
        {
            _repository = repository;
            this.db = db;
        }

        public IActionResult NewInstructor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewInstructor(NewInstructorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newInstructor = new Instructors()
                {
                    first_name = model.FirstName,
                    last_name = model.LastName,
                    experience = model.Experience,
                    enrollment_date = model.Enrollmentdate,
                    created_at = DateTime.Now
                };

                _repository.AddEntity(newInstructor);

                _repository.SaveAll();
            }
            else
            {
                //show errors
            }

            return RedirectToAction("InstructorManagement");

        }

        [Authorize]
        public IActionResult InstructorManagement(string searchString)

        {
            var results = /*from p in _context*/_repository/*.Products*/.GetAllInstructors();
            //orderby p.Category
            //select p;

            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                results = results.Where(s => s.last_name.Contains(searchString)
                                       || s.first_name.Contains(searchString));
            }

            return View(results.ToList());
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.GetAllInstructors().Where(s => s.instructor_id == id).FirstOrDefault();

            return View(usr);
        }

        [HttpPost]
        public ActionResult Edit(Instructors inst)
        {
            //update user in DB using EntityFramework in real-life application

            //update list by removing old user and adding updated user for demo purpose
            var instructor = _repository.GetAllStudents().Where(s => s.student_id == inst.instructor_id).FirstOrDefault();
            _repository.RemoveEntity(instructor);
            _repository.AddEntity(inst);
            _repository.SaveAll();

            return RedirectToAction("InstructorManagement");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            //here, get the student from the database in the real application
            //getting a student from collection for demo purpose
            var std = _repository.GetAllInstructors().Where(s => s.instructor_id == id).FirstOrDefault();
            return View(std);
        }

        [HttpPost]
        public ActionResult Delete(Instructors inst)
        {
            //update student in DB using EntityFramework in real-life application

            //update list by removing old student and adding updated student for demo purpose
            var user = _repository.GetAllInstructors().Where(s => s.instructor_id == inst.instructor_id).FirstOrDefault();
            _repository.RemoveEntity(user);
            _repository.SaveAll();

            return RedirectToAction("InstructorManagement");
        }

    }

}

Controllers/StudentController.cs
using AceSchoolPortal.Data;
using AceSchoolPortal.Data.Entities;
using AceSchoolPortal.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class StudentController : Controller
    {
        private readonly ISchoolRepository _repository;
        private readonly SchoolContext db;

        public StudentController(ISchoolRepository repository, SchoolContext db)
        {
            _repository = repository;
            this.db = db;
        }

        public IActionResult NewStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewStudent(NewStudentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newStudent = new Students()
                {
                    first_name = model.FirstName,
                    last_name = model.LastName,
                    enrollment_date = model.DOJ,
                    dob = model.DOB,
                    grade = model.Grade,
                    address = model.Address
                };

                _repository.AddEntity(newStudent);

                _repository.SaveAll();
            }
            else
            {
                //show errors
            }

            return RedirectToAction("StudentManagement");

        }

        [Authorize]
        public IActionResult StudentManagement(string searchString, int? page, string currentFilter)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            var results = /*from p in _context*/_repository/*.Products*/.GetAllStudents();
            //orderby p.Category
            //select p;

            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                results = results.Where(s => s.last_name.Contains(searchString)
                                       || s.first_name.Contains(searchString));
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(results.ToPagedList(pageNumber,pageSize));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.GetAllStudents().Where(s => s.student_id == id).FirstOrDefault();
            return View(usr);
        }

        [HttpPost]
        public IActionResult Edit(Students std)
        {
            //update user in DB using EntityFramework in real-life application

            //update list by removing old user and adding updated user for demo purpose
            var student = _repository.GetAllStudents().Where(s => s.student_id == std.student_id).FirstOrDefault();
            _repository.RemoveEntity(student);
            _repository.AddEntity(std);
            _repository.SaveAll();

            return RedirectToAction("StudentManagement");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            //here, get the student from the database in the real application
            //getting a student from collection for demo purpose
            var std = _repository.GetAllStudents().Where(s => s.student_id == id).FirstOrDefault();
            return View(std);
        }

        [HttpPost]
        public ActionResult Delete(Students std)
        {
            //update student in DB using EntityFramework in real-life application

            //update list by removing old student and adding updated student for demo purpose
            var user = _repository.GetAllStudents().Where(s => s.student_id == std.student_id).FirstOrDefault();
            _repository.RemoveEntity(user);
            _repository.SaveAll();

            return RedirectToAction("StudentManagement");
        }

    }

}

Controllers/SubjectsController.cs
using AceSchoolPortal.Data;
using AceSchoolPortal.Data.Entities;
using AceSchoolPortal.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISchoolRepository _repository;
        private readonly SchoolContext db;

        public SubjectsController(ISchoolRepository repository, SchoolContext db)
        {
            _repository = repository;
            this.db = db;
        }

        public IActionResult NewSubject()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewSubject(NewSubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newSubject = new Subjects()
                {
                    subject_name = model.SubjectName,
                    // created date should be the date as created
                    created_at = DateTime.Now,
                    // updated date should be same as created date before it gets updated 
                    updated_at = DateTime.Now
                };

                _repository.AddEntity(newSubject);

                _repository.SaveAll();
            }
            else
            {
                //show errors
            }

            return RedirectToAction("SubjectMngmnt");

        }

        [Authorize]
        public IActionResult SubjectMngmnt(string searchString, int? page, string currentFilter)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            var results = /*from p in _context*/_repository/*.Products*/.GetAllSubjects();
            //orderby p.Category
            //select p;

            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                results = results.Where(s => s.subject_name.Contains(searchString));
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(results.ToPagedList(pageNumber,pageSize));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.GetAllSubjects().Where(s => s.subject_id == id).FirstOrDefault();
            return View(usr);
        }

        [HttpPost]
        public IActionResult Edit(Subjects sub)
        {
            //update subjects in DB using EntityFramework in real-life application

            //update list by removing old user and adding updated user for demo purpose
            var subject = _repository.GetAllSubjects().Where(s => s.subject_id == sub.subject_id).FirstOrDefault();
            _repository.RemoveEntity(subject);
            // created date should remain the same
            sub.created_at = subject.created_at;
            // edited/updated date should be updated to current date (date of the edit)
            sub.updated_at = DateTime.Now;
            _repository.RemoveEntity(subject);
            _repository.AddEntity(sub);
            _repository.SaveAll();

            return RedirectToAction("SubjectMngmnt");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            //here, get the student from the database in the real application
            //getting a student from collection for demo purpose
            var sub = _repository.GetAllSubjects().Where(s => s.subject_id == id).FirstOrDefault();
            return View(sub);
        }

        [HttpPost]
        public ActionResult Delete(Subjects sub)
        {
            //update student in DB using EntityFramework in real-life application

            //update list by removing old student and adding updated student for demo purpose
            var subject = _repository.GetAllSubjects().Where(s => s.subject_id == sub.subject_id).FirstOrDefault();
            _repository.RemoveEntity(subject);
            _repository.SaveAll();

            return RedirectToAction("SubjectMngmnt");
        }

    }

}

Views/App/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model NewRegstnViewModel
@{
    ViewBag.Title = "Registration Page";
}
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-6 offset-md-3">
    <div class="card card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>

            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="FirstName">First Name:</label>
                    <input asp-for="FirstName" type="text" class="form-control">
                    <span asp-validation-for="FirstName"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="LastName">Last Name:</label>
                    <input asp-for="LastName" type="email" class="form-control">
                    <span asp-validation-for="LastName"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="Email">Email Address:</label>
                    <input asp-for="Email" type="text" class="form-control">
                    <span asp-validation-for="Email"></span>
                </div>
            </div>
            @*<div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="UserName">Username:</label>
                    <input asp-for="UserName" type="text" class="form-control">
                    <span asp-validation-for="UserName"></span>
                </div>
            </div>*@
            <div class="form-group">
                <div class="col-md-12 col-lg-12 col-xs-12">
                    <label asp-for="Password">Password:</label>
                    <input name="Password" type="password" class="form-control">
                    <span asp-validation-for="Password"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 col-lg-12 col-xs-12">
                    <label asp-for="ContactNo">Password:</label>
                    <input name="ContactNo" type="number" class="form-control">
                    <span asp-validation-for="ContactNo"></span>
                </div>
            </div>
            <br>
            <div class="col-md-12 col-lg-12 col-xs-12">
                <button type="submit" class="btn btn-warning">Submit</button>
                <div>@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

Views/App/Delete.cshtml
@model Users
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.FirstName)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.isEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.isEnabled, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.isEnabled, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/App/Edit.cshtml
@model Users
@{
    ViewBag.Title = "Edit";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{


<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.FirstName)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.isEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.isEnabled, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.isEnabled, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/App/Home.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "HomePage";
}
    <center>
        <h1> Welcome to Ace School Portal </h1>
        <div class="product-info">
            <button class="btn btn-secondary"><a asp-controller="App" asp-action="UserManagement" class="nav-link" style="color:lightskyblue">User Management</a></button>
            <button class="btn btn-secondary"><a asp-controller="Student" asp-action="StudentManagement" class="nav-link" style="color:lightgreen">Students Management</a></button>
            <br />
            <br />
            <button class="btn btn-secondary"><a asp-controller="Instructor" asp-action="InstructorManagement" class="nav-link" style="color:lightcoral">Instructors Management</a></button>
            <button class="btn btn-secondary"><a asp-controller="Subjects" asp-action="SubjectMngmnt" class="nav-link" style="color:lightyellow">Subjects Management</a></button>
            <br />
            <br />
            <button class="btn btn-secondary"><a asp-controller="ClassGrades" asp-action="ClassGradesMngmnt" class="nav-link" style="color:lightskyblue">Class Grade Management</a></button>
        </div>
    </center>

Views/App/NotEnabled.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "HomePage";
}
    <center>
        <h1> Welcome to Ace School Portal </h1>
        <h1> It Appers that you are still not Enabled - Pending Approval </h1>
        <div class="product-info">           
            <button class="btn btn-warning"><a asp-controller="App" asp-action="index" style="color:black"> Go Back </a></button>
        </div>
    </center>

Views/App/UserManagement.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Users>
<h1>User Management</h1>
<p>Users Count: @Model.Count()</p>
<div>
    <button class="btn btn-dark"><a asp-controller="App" asp-action="NewRegistration" class="nav-link">Add New User</a></button>
    <br />
    <br />
    <center>
        <form asp-action="UserManagement" method="get">
            <div class="form-actions no-color">
                <p>
                    Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-default" /> |
                    <a asp-action="UserManagement">Back to Full List</a>
                </p>
            </div>
        </form>
        <table class="table table-striped table-bordered" style="margin-left:30px;margin-right:30px">
            <thead class="thead-dark">
                <tr>
                    <th> FirstName </th>
                    <th> LastName </th>
                    <th> EmailAddress </th>
                    <th> ContactNo  </th>
                    <th> isAdmin </th>
                    <th> isEnabled </th>
                    <th style="color:darkcyan"> Update </th>
                    <th style="color:darkcyan"> Delete </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                    <tr>
                        <td nowrap="">  @p.FirstName </td>
                        <td nowrap="">  @p.LastName </td>
                        <td nowrap="">  @p.EmailAddress </td>
                        <td nowrap="">  @p.ContactNo  </td>
                        <td nowrap="">  @p.isAdmin </td>
                        <td nowrap="">  @p.isEnabled </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = p.UserName })
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = p.UserName })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </center>
</div>

Views/App/index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "HomePage";
}
    <center>
        <h1> Welcome to Ace School Portal </h1>
        <div class="product-info">
            <button class="btn btn-secondary" ><a asp-controller="Account" asp-action="Login" style="color:white"> Login </a></button>
            <button class="btn btn-warning"><a asp-controller="Account" asp-action="NewRegistration" style="color:black"> New Registration </a></button>
        </div>
    </center>